PySide/pyside2

PySide2/QtCore/typesystem_core_x11.xml

Correct fix for failing builds on Linux
However, I wonder, whether it is possible to inherit "QSysInfo" from common and add just the specific lines for OSX and WIN. My XML skills are just good enough to copy+past this missing part.

Adding missing QSysInfo to typesystem_core_x11

---

PySide2/QtGui/glue/qguiapplication_init.cpp
PySide2/QtGui/typesystem_gui_common.xml

If you try and instantiate `QGuiApplication`, PySide2 will segfault because it tries to set the `qGuiApp` property of the `QtGui` module, but that property wasn't initialized yet. [Looking at the documentation](http://doc.qt.io/qt-5/qguiapplication.html), this module doesn't seem to have any application-related macros anyway so this PR just removes the `qGuiApp` stuff.

Fix segfault when instantiating QGuiApplication

---

PySide2/CMakeLists.txt
PySide2/QtQml/CMakeLists.txt
PySide2/QtQml/pysideqmlregistertype.cpp
PySide2/QtQml/pysideqmlregistertype.h
PySide2/QtQml/typesystem_qml.xml
PySide2/QtQuick/CMakeLists.txt
PySide2/QtQuick/typesystem_quick.xml
PySide2/QtQuickWidgets/CMakeLists.txt
PySide2/QtQuickWidgets/typesystem_quickwidgets.xml
PySide2/global.h.in

This PR adds the following modules:
* QtQuick (*partially*)
* QtQml
* QtQuickWidgets
I could *not* wrap my head around a lot of the classes in Qml and Quick - I hope that someone else might know better how to do these! Because of these issues, I did not yet add all the scenegraph (QSG*) classes to QtQuick as I figured it made sense to focuse on the Qml stuff for now. Though if you'd like the whole thing wrapped before commiting I can do that
I also ported `qmlRegisterType` over from the old QtDeclarative module. It was surprisingly easy, and seems to work fine after some superficial testing in the Python REPL but definitely gonna need to get the unit tests up and running!
The `QJSEngine` class also contains a wrapper around the template function `toScriptValue` - I have not yet done …

Add Qt5 QML modules

---

PySide2/CMakeLists.txt
PySide2/QtWebSockets/typesystem_websockets.xml
PySide2/global.h.in

It now builds successfully (also added a missing class and namespace) - but the ssl-related functions needed to be rejected for now. For some reason, when building QtNetwork, Shiboken's not picking up the SSL-related classes like QSslConfiguration and it's causing this module to fail with those functions enabled.

Fix up the QtWebSockets module

---

libpyside/pysidemetafunction.cpp
libpyside/signalmanager.cpp

This *should* fix slots that don't have a return type. I've yet to mess around much with the property decorator

Fix void return type on slots

---

PySide2/QtCore/CMakeLists.txt
PySide2/QtCore/typesystem_core_common.xml

Final bit of tweaking that was needed to get QWebChannel support working nicely.
Example: If you got this object from a page:
```json
{
"hello": "world",
"number": 123,
"array": [1, 2, 3],
"nullValue": null
}
```
You'll get this Python dict:
```python
{
"hello": "world",
"number": 123,
"array": [1, 2, 3],
"nullValue": None
}
```
The JSON classes have a to and from variant method, so this conversion just piggy backs off of pyside's existing Variant<>Python support.
And it turns a dict into a QJsonObject too! If you provide it with some none-serializable object, it will just get eaten up and turned into a null.

Add basic automatic QJsonObject <-> dict conversion

---

PySide2/QtCore/typesystem_core_common.xml

This fixes the segfault that causes the test `QtCore/bug_515.py` to fail.

Ensure the GIL in globalPostRoutineCallback()

---

tests/QtCore/bug_606.py
tests/QtCore/bug_826.py
tests/QtCore/repr_test.py
tests/QtCore/versioninfo_test.py
tests/QtGui/bug_606.py
tests/QtGui/qcolor_test.py
tests/QtGui/repr_test.py
tests/pysidetest/utils_test.py
tests/tools/list-class-hierarchy.py
tests/util/color.py
tests/util/pyqt_diff.py

There were still some attempts to import `PySide` which was causing a couple of tests to fail. Also updated the PyQt<->PySide comparison tools

Fix outdated module names in tests

---

PySide2/CMakeLists.txt
tests/QtQml/bug_847.py

Not all tests were getting picked up by the CMake file for the tests, because the variables being set by `find_package` in the `pyside2/PySide2` CMake file were not being hoisted to the parent scope.
The tests that were running already are running because other parts of the CMake script were doing things like `find_package(Qt5Core)` for other things.
This brings the number of tests from 356 to 390, and unfortunately the percentage of passing tests down from 81% to 78% :(
Also added a timeout to a Qml test because it hangs after a while.

Fix missing tests

---

libpyside/dynamicqmetaobject.cpp

This adds the following patch from the old PySide Gerrit:
https://codereview.qt-project.org/#/c/84452/
@pankajp's description of the patch:
> PropertyData::type() returns a new QByteArray (whose `data` is a
> copy of the `char*` name of the property)
> However the use of `type().data()` on the stack without saving
> its reference means the `char*` returned by the `data()` method
> is immediately deallocated in the the `~QByteArray` destructor.
> (Detected by AddressSanitizer)
> The attached patch fixes it by holding a reference to the
QByteArray returned by `type()` for the duration of the method call

Fix use-after-free in QProperty

---

libpyside/pysidesignal.cpp
tests/signals/CMakeLists.txt
tests/signals/bug_189.py

This PR merges this patch from the old Gerrit (and also updates the unit test in it to PySide2):
https://codereview.qt-project.org/#/c/110414/
Original description:
> When disconnecting a signal on object that has been destroyed the
> disconnect call (Sbk_QObjectFunc_disconnect) fails and returns 0 with an
> error set. The calling function (signalInstanceDisconnect) was
> segfaulting because it decrements the reference count of the returned
> value. As the Python error is already set it's sufficient for
> signalInstanceDisconnect to return 0 in this case.
Pinging the original contributor, @tonyroberts, so he's aware of this.

Fix segfault when disconnecting signal on deleted object

---

tests/signals/CMakeLists.txt

I ran the test manually, so didn't catch that the name I put in the cmakelist was wrong.

Fix improper test filename

---

libpyside/signalmanager.cpp.in

The private APIs changed around a little bit in Qt 5.6. `currentContext()` is no longer a function and does something else, but the member `current` is the same on 5.6 and older versions.

Fix private API usage for Qt 5.6

---

libpyside/signalmanager.cpp.in

Hi,
"strong enums" are not accessible with GCC with default standard (before c++11). The fix is to use transitional syntax.
Cheers,
Mateusz

Fix bug #54.

---

plugins/customwidget.cpp
plugins/customwidget.h
plugins/customwidgets.cpp
plugins/customwidgets.h

Use QtUiPlugin/QDesignerCustomWidgetInterface instead.

Header <QtDesigner/QDesignerCustomWidgetInterface> is deprecated in Qt5.5.

---

libpyside/signalmanager.cpp.in

1. Heap namespace has been introduced in Qt 5.5.0.
2. Throw methods have been moved from ExecutionContext to ExecutionEngine in Qt 5.5.0.
Source 1: https://github.com/qtproject/qtdeclarative/commit/84aae25c0b3003fb846568cf26a2c7150db14d9d
Source 2: https://github.com/qtproject/qtdeclarative/commit/486948817b26da2c62802bb93a0f671715c609d4
Tested on Debian only.
GCC 4.9.2 and Qt 5.3.2
GCC 5.3.1 and Qt 5.5.1
Cheers,
Mateusz

Fix building signalmanager.cpp with Qt < 5.5.0.

---

libpyside/signalmanager.cpp.in

Hi,
compilation tested on:
Debian GCC 4.9.2 and Qt 5.3.2
Ubuntu GCC 5.2.1 and Qt 5.4.2
Debian GCC 5.3.1 and Qt 5.5.1
Cheers,
Mateusz

Fix building signalmanager.cpp with Qt 5.4.x.

---

PySide2/CMakeLists.txt
PySide2/QtGui/CMakeLists.txt
PySide2/QtWidgets/typesystem_widgets_x11.xml
PySide2/QtX11Extras/CMakeLists.txt
PySide2/QtX11Extras/typesystem_x11extras.xml
PySide2/global.h.in

Debian based systems need libqt5x11extras5-dev package installed.
Debian GCC 4.9.2, Qt 5.3.2, Python 2.7.9 64-bit 
Ubuntu GCC 5.2.1, Qt 5.4.2, Python 2.7.10 64-bit
Debian GCC 5.3.1, Qt 5.5.1, Python 2.7.11 64-bit
Cheers,
Mateusz

Add support for Qt X11 Extras module.

---

PySide2/CMakeLists.txt

X11Extras module is not required on linux. There are at least two cases:
X11 is not installed, for example, on some embeded linux, linux using wayland instead of X11, or all custom Qt QPA backend (see "-platform" when building qt-base)
X11 is installed but Qt5 X11Extra is not installed. It is the case for example if only qt-base is built
Use upper case to respect convention used in all previous calls of CHECK_PACKAGE_FOUND

Qt5X11Extras becomes optional. make command upper case.

---

PySide2/QtCore/typesystem_core_common.xml

Registered as a metatype QVector<int> so the dataChanged signal from QAbstractItemModel can be used. Still have to specify the third argument as an empty list
(Cleaner pull request than the previous one)

Added registration of QVector<int> as a metatype in QAbstractItemModel
